export const UPDATE_ALGORITHM =  "UPDATE_ALGORITHM";
export const UPDATE_START_NODE =  "UPDATE_START_NODE";
export const UPDATE_FINISH_NODE =  "UPDATE_FINISH_NODE";
export const VISUALIZE_ALGORITHM =  "VISUALIZE_ALGORITHM";
